r"""
Module to generate serving extras.

This script creates additional datasets specifically needed by the API/Dashboard:
- latest_jobs: The 50 most recent jobs. It must be generated by re-reading the raw jobs CSV 
  because the processed/jobs dataset loses the raw skills string (which is required by the UI). 
  The tie rule for sorting jobs with the exact same postdate is to sort by `row_id` ascending 
  (where `row_id` is the 0-based index of the row in the CSV) to ensure a stable, deterministic result.
- courses: A direct copy of the processed/courses dataset containing course details with original-case skill tags.
"""
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(repo_root))

from pyspark.sql import functions as F
from pyspark.sql.window import Window

from src.common.config import get_path
from src.common.logging_setup import get_logger
from src.common.spark_session import get_spark

logger = get_logger("serving_extras")

def main():
    spark = get_spark("ServingExtras")
    try:
        analytics_base = get_path("analytics").rstrip("/")

        # 1. Latest Jobs
        logger.info("Reading raw jobs from %s", get_path("raw/jobs"))
        raw_jobs_df = spark.read.csv(
            get_path("raw/jobs"),
            header=True,
            inferSchema=False,
            multiLine=True,
            quote='"',
            escape='"'
        )
        
        if raw_jobs_df.rdd.isEmpty():
            logger.error("Raw jobs dataset is empty.")
            sys.exit(1)
            
        raw_jobs_df = raw_jobs_df.fillna("")
        
        # Add a sequential row_id starting from 0 to preserve original CSV order
        # Note: monotonically_increasing_id() is not consecutive, so we use row_number() over it.
        # This requires moving data to a single partition, but jobs dataset is small enough.
        w = Window.orderBy(F.monotonically_increasing_id())
        jobs_with_id = raw_jobs_df.withColumn("row_id", F.row_number().over(w) - 1)
        
        # Calculate location: text before the first comma of joblocation_address, trimmed; "Unknown" if empty
        location_expr = F.trim(F.element_at(F.split(F.col("joblocation_address"), ","), 1))
        jobs_with_location = jobs_with_id.withColumn(
            "location",
            F.when((location_expr == "") | location_expr.isNull(), "Unknown").otherwise(location_expr)
        )
        
        # Select required columns
        latest_jobs = jobs_with_location.select(
            "row_id",
            F.col("jobtitle"),
            F.col("company"),
            "location",
            F.col("skills"),
            F.col("experience"),
            F.col("postdate")
        )
        
        # Sort postdate descending then row_id ascending, limit 50
        latest_jobs = latest_jobs.orderBy(F.col("postdate").desc(), F.col("row_id").asc()).limit(50)
        
        latest_jobs_path = f"{analytics_base}/latest_jobs"
        latest_jobs.write.parquet(latest_jobs_path, mode="overwrite")
        logger.info("Wrote %d rows to latest_jobs at %s", latest_jobs.count(), latest_jobs_path)
        
        # 2. Courses
        logger.info("Reading processed courses from %s", get_path("processed/courses"))
        courses_df = spark.read.parquet(get_path("processed/courses"))
        
        if courses_df.rdd.isEmpty():
            logger.error("Processed courses dataset is empty.")
            sys.exit(1)
            
        # Select required columns (same as processed/courses)
        courses_out = courses_df.select(
            "course_id",
            "name",
            "source",
            "domain",
            "url",
            "institution",
            "duration_weeks",
            "difficulty",
            "skill_tags",
            "syllabus_weeks"
        )
        
        courses_path = f"{analytics_base}/courses"
        courses_out.write.parquet(courses_path, mode="overwrite")
        logger.info("Wrote %d rows to courses at %s", courses_out.count(), courses_path)
        
    except Exception as e:
        logger.error("Error generating serving extras: %s", e, exc_info=True)
        sys.exit(1)
    finally:
        spark.stop()

if __name__ == "__main__":
    main()
